version: "3.6"

services:
  web:
    build: .
    image: "cornellappdev/pear"
    env_file: node.env
    ports:
      - "80:5000"
    networks:
      - main
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: any
  postgres:
        container_name: postgres
        hostname: postgres
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=pear
        networks:
            - main
        ports:
            - "5432:5432"
        restart: on-failure

networks:
    main:
